# Generated by Django 6.0.1 on 2026-03-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0003_siteconfig_cv_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='education_text',
            field=models.TextField(default='Currently pursuing <strong>B.Tech in Computer Science & Engineering</strong> at <strong>Lovely Professional University</strong>, Phagwara, Punjab with a CGPA of <strong>6.5</strong>. Passionate about cybersecurity, ethical hacking, and building secure full-stack applications.', help_text='HTML allowed. Displayed below bio in the About section.'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='stat1_label',
            field=models.CharField(blank=True, default='CGPA', max_length=50),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='stat1_value',
            field=models.CharField(blank=True, default='6.5', max_length=30),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='stat2_label',
            field=models.CharField(blank=True, default='HackerRank', max_length=50),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='stat2_value',
            field=models.CharField(blank=True, default='Top 10%', max_length=30),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='stat3_label',
            field=models.CharField(blank=True, default='Certificates', max_length=50),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='stat3_value',
            field=models.CharField(blank=True, default='3+', max_length=30),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='stat4_label',
            field=models.CharField(blank=True, default='Projects', max_length=50),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='stat4_value',
            field=models.CharField(blank=True, default='2+', max_length=30),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='tags',
            field=models.CharField(default='JavaScript,Python,C++,Cybersecurity,MERN Stack,Django,Kali Linux', help_text='Comma-separated tags shown as floating badges in the About section.', max_length=500),
        ),
    ]
